Controllers/CitasController.cs
using MedControlNet.Entities;
using MedControlNet.Models;
using MedControlNet.Services;
using NLog;
using System;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;

using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;
using SelectListItem = System.Web.Mvc.SelectListItem;

namespace MedControlNet.Controllers
{
    public class CitasController : Controller
    {
        private static readonly Logger Logger = NLog.LogManager.GetCurrentClassLogger();

        private readonly CitasServicio _citasServicio;
        private readonly MedicosServicio _medicosServicio;

        public CitasController(CitasServicio citasServicio, MedicosServicio medicosServicio)
        {
            _citasServicio = citasServicio;
            _medicosServicio = medicosServicio;
        }

        public ActionResult Index()
        {

            ModelState.Merge(TempData["modelState"] == null ? ModelState : (System.Web.Mvc.ModelStateDictionary)TempData["modelState"]);

            var citaFormulario = TempData["form"] != null ? (CitaFormularioModelo)TempData["form"] : new CitaFormularioModelo();

            var medicosLista = _medicosServicio.ObtenerMedicos();
            var items = medicosLista.Select(medico => new SelectListItem()
            {

                Selected = medico.MedicoId + "" == citaFormulario.MedicoEspecialista,
                Text = $"{medico.Nombre} ({medico.EspecialidadModel.NombreEspecialidad})",
                Value = medico.MedicoId.ToString()

            }).ToList();

            if (citaFormulario.FechaCita < DateTime.Now)
            {
                citaFormulario.FechaCita = DateTime.Now;
            }


            items.Insert(0, new SelectListItem()
            {
                Text = "Seleccione",
                Value = "-1"
            });
            var citaModelo = new CitaModelo()
            {
                medicos = items,
                consultorios = null,
                CitaFormularioModelo = citaFormulario
            };

            return View(citaModelo);
        }


        [HttpPost]
        public ActionResult Index(CitaFormularioModelo citaModelo)
        {

            if (ModelState.IsValid)
            {
                var fechaSeleccionada = citaModelo.FechaCita;


                if (NoEsHoraDeAlmuerzo(fechaSeleccionada))
                {
                    TempData["MensajeError"] = $"La fecha seleccionada '{citaModelo.FechaCita}' no es válida. La hora de almuerzo es de las 12pm a 1pm ";
                    TempData["form"] = citaModelo;
                    return RedirectToAction("Index");
                }

                if (NoEsHorarioValido(fechaSeleccionada))
                {
                    TempData["MensajeError"] = $"La fecha seleccionada '{citaModelo.FechaCita}' no es válida. El horario de atención 8am a 5pm. ";
                    TempData["form"] = citaModelo;
                    return RedirectToAction("Index");
                }

                try
                {
                    TempData["form"] = null;
                    _citasServicio.AgregarCita(citaModelo);
                    TempData["MensajeExito"] = $"La cita de {citaModelo.NombrePaciente} con cédula {citaModelo.CedulaPaciente} se ha agendado satisfactoriamente";
                }
                catch (CitaExisteExcepcion ex)
                {

                    TempData["MensajeError"] = ex.Message;
                    TempData["form"] = citaModelo;
                    TempData["modelState"] = ModelState;
                }

                return RedirectToAction("Index");
            }

            TempData["MensajeError"] = "Hay campos con errores";
            TempData["form"] = citaModelo;
            TempData["modelState"] = ModelState;
            return RedirectToAction("Index");
        }

        private bool NoEsHoraDeAlmuerzo(DateTime fechaSeleccionada)
        {

            return fechaSeleccionada.Hour >= 12 && fechaSeleccionada.Hour < 13;
        }

        private bool NoEsHorarioValido(DateTime fechaSeleccionada)
        {


            return !(fechaSeleccionada.Hour >= 9 && fechaSeleccionada.Hour < 17);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Control Médico</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="d-flex d-inline-flex">
                <button class="btn d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Control Médico", "Index", "Home", new { }, new { @class = "navbar-brand" })
            </div>

        </div>
    </nav>

    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasLabel">Menú</h5>
            <button type="button" class="btn-close text-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            @Html.Partial("_SideBar")
        </div>
    </div>


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 min-vh-100 d-none d-md-block bg-light border-1 border-end">
                @Html.Partial("_SideBar")
            </div>
            <div class="col">
                <div class="container pt-md-0 pt-4 bg-white">
                    @RenderBody()
                </div>

                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - MedControlNet</p>
                </footer>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_SideBar.cshtml
@{
    var controller = ViewContext.RouteData.Values["Controller"];
    var action = ViewContext.RouteData.Values["Action"];
    var selected = $"{controller}/{action}";
}
<ul class="nav nav-pills flex-column mt-md-3">
    <li class="nav-item">
        @Html.ActionLink("Inicio", "Index", "Home", new { }, new { @class = $"nav-link {(selected == "Home/Index" ? "active" : "")}" })
    </li>
    <li class="nav-item">
        @Html.ActionLink("Gestión de Especialistas", "Index", "Especialistas", new { }, new { @class = $"nav-link {(selected == "Especialistas/Index" ? "active" : "")}" })
    </li>
    <li class="nav-item">
        @Html.ActionLink("Gestión de Inventario", "Index", "Inventarios", new { }, new { @class = $"nav-link {(selected == "Inventarios/Index" ? "active" : "")}" })
    </li>
    <li class="nav-item">
        @Html.ActionLink("Gestión de Consultorios", "Index", "Consultorios", new { }, new { @class = $"nav-link {(selected == "Consultorios/Index" ? "active" : "")}" })
    </li>
    <hr />
    <li class="nav-item">
        @Html.ActionLink("Control de Citas", "Index", "Citas", new { }, new { @class = $"nav-link {(selected == "Citas/Index" ? "active" : "")}" })
    </li>
    <hr />

    <li class="nav-item">
        @Html.ActionLink("Reportes", "Index", "Reportes", new { }, new { @class = $"nav-link {(selected == "Reportes/Index" ? "active" : "")}" })
    </li>

</ul>