Entities/Consultorio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedControlNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultorio()
        {
            this.Especialidads = new HashSet<Especialidad>();
            this.Inventarios = new HashSet<Inventario>();
            this.Citas = new HashSet<Cita>();
        }
    
        public int ConsultorioID { get; set; }
        public Nullable<int> NumeroConsultorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialidad> Especialidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
    }
}

Controllers/ConsultoriosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MedControlNet.Entities;
using MedControlNet.Models;
using MedControlNet.Services;

namespace MedControlNet.Controllers
{
    public class ConsultoriosController : Controller
    {

        private readonly ConsultoriosServicio _consultoriosServicio;

        public ConsultoriosController(ConsultoriosServicio consultoriosServicio)
        {
            _consultoriosServicio = consultoriosServicio;
        }

        public ActionResult Index()
        {
            return View(_consultoriosServicio.ObtenerConsultorios());
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(_consultoriosServicio.ObtenerConsutultorioPorId(id));

        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "ConsultorioID,NumeroConsultorio")] ConsultorioModelo consultorioModelo)
        {
           
            if (ModelState.IsValid)
            {

                _consultoriosServicio.ActualizarConsultorio(consultorioModelo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AgregarEspecialidad(ConsultorioModelo consultorioModelo) {

            _consultoriosServicio.AgregarEspecialidad(consultorioModelo);

            return RedirectToAction($"Edit/{consultorioModelo.ConsultorioID}");
        }

        public ActionResult EliminarEspecialidad(int? especialidadId, int? consultorioId) {

            _consultoriosServicio.RemoverEspecialidad(especialidadId, consultorioId);

            return RedirectToAction($"Edit/{consultorioId}");
        }

    }
}

Views/Consultorios/Edit.cshtml
@model MedControlNet.Models.ConsultorioModelo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-3">Editar consultorio</h2>


    
<div class="form-horizontal">
    <hr />
    @using (Html.BeginForm("Edit", "Consultorios", FormMethod.Post, new { @id = "formConsultorio" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ConsultorioID)

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroConsultorio, "Número de consultorio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NumeroConsultorio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroConsultorio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mt-5">
            <h5>Especialidades del consultorio</h5>


            <div class="col-6 mt-3">
                <table class="table">
                    <thead class="table-primary">
                        <tr>
                            <th scope="col">Especialidad</th>
                            <th scope="col">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.EspecialidadesConsultorio)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombreEspecialidad)
                                </td>
                                <td>
                                    @Html.ActionLink("Eliminar", "EliminarEspecialidad", new { especialidadId = item.EspecialidadID, consultorioId = Model.ConsultorioID }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>

            </div>


        </div>
    }



            @using (Html.BeginForm("AgregarEspecialidad", "Consultorios", FormMethod.Post, new { @id = "formAgregarEspecialidad" }))
            {
                <div class="row">
                    <div class="col-3">
                        @Html.HiddenFor(model => model.ConsultorioID)
                        @Html.DropDownList("NuevaEspecialidad", Model.TodasLasEspecialidades, new { @class = "form-select" })
                    </div>
                    <div class="col">
                        <input type="submit" value="Añadir" class="btn btn-primary" />
                    </div>
                </div>

            }






    <div class="form-group">
        <div class="col-md-offset-2 col-md-6 text-end mt-5">
            @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-secondary" })
            <input type="submit" form="formConsultorio" value="Actualizar consultorio" class="btn btn-primary" />
        </div>
    </div>
</div>


<div>
   
</div>

Views/Consultorios/Index.cshtml
@model IEnumerable<MedControlNet.Entities.Consultorio>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-7">



        <h2 class="mt-5">Todos los consultorios</h2>

        <table class="table ">

            <thead class="table-primary">
                <tr>
                    <th scope="col">Número de consultorio</th>
                    <th scope="col">Opciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @{
                                var especialidades = item.Especialidads.Select(esp => esp.NombreEspecialidad).ToList();
                                var especialidadesAMostrar = string.Join(", ", especialidades);

                            }
                            @Html.DisplayFor(modelItem => item.NumeroConsultorio)
                            @if (especialidadesAMostrar.Length > 0)
                            {
                                <span class="ms-2 fw-bold">(@especialidadesAMostrar)</span>
                            }


                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.ConsultorioID }, new { @class = "btn btn-secondary" })
                        </td>
                    </tr>
                }

            </tbody>

        </table>
    </div>

</div>